### ISSUE TITLE
Nonfunctional with Elite Variety

### ISSUE THREAD

**Issue by GalacticRuler** [TheMysticSword/AspectAbilities#19]
For some reason, the most recent versions of both of these mods installed at the same time causes all aspects to lose their active effects

EDIT: 
[LogOutput.log](https://github.com/TheMysticSword/AspectAbilities/files/6873234/LogOutput.log)

**Comment by GalacticRuler** [comment]
Log file attached finally

**Comment by TheMysticSword** [comment]
AspectAbilities is not mentioned in the log at all - are you *sure* it's installed and enabled?

**Comment by GalacticRuler** [comment]
I completely forgot we removed it before that run-
However, it was removed because it wasn't working. I can reinstall and see if it works, but if not I'll drop a fresh log here

**Comment by GalacticRuler** [comment]
huh....it all works?
Very strange that it wasn't for some reason
