### ISSUE TITLE
Droprate Up !

### ISSUE THREAD

**Issue by benjdidj** [TheMysticSword/AspectAbilities#6]
Could you add cfg file to change aspects drop rates ? Your mod makes dropping an aspect make sense, if only the drop rate was higher. Thx for ur mod.

**Comment by TheMysticSword** [comment]
Thanks for the suggestion! I'd like to keep this mod only as "aspects have use abilities" without additional features, so right now I'm considering two options:
* Making a mod that adds some kind of a guaranteed way to get aspects (more fun, but requires more effort)
* A separate mod that lets you increase the droprate through a config (simple, easy to make, but requires having same config for all people in a multiplayer lobby)

**Comment by benjdidj** [comment]
thx for the answer .

**Comment by TheMysticSword** [comment]
Done. This mod lets you change the aspect drop rate with a config.
https://thunderstore.io/package/TheMysticSword/ConfigAspectDropChance/

**Comment by benjdidj** [comment]
wow thx
